;Constants

; VRAM tiles
TILE_HP_SQUARE EQU $68
TILE_BOSS_HP EQU $69
TILE_BOSS EQU $6a
TILE_SC EQU $6c
TILE_LIFE_ICON equ $67
TILE_HP_DOT EQU $6e
TILE_KIRBY_TEXT equ $6f
TILE_LIFE_CROSS equ $6b
TILE_ZERO EQU $72

TILE_EMPTY EQU $7f
